/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penyilihan;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import model.koneksipbo;

/**
 *
 * @author Mik
 */
public class loginx extends javax.swing.JFrame {

    koneksipbo con;
    boolean check = false;

    public loginx() {
        initComponents();
        setLocationRelativeTo(this);
        con = new koneksipbo();
        logine.addActionListener(new LoginListener());
    }

    public String getUsername() {
        return nama1.getText();
    }

    public String getPassword() {
        String pass = "";
        char passArray[] = password.getPassword();
        for (int i = 0; i < passArray.length; i++) {
            pass += passArray[i];
        }
        return pass;
    }

    //   public void loginListener (ActionListener listener){
    //       logine.addActionListener(listener);
//}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        nama1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        logine = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/SELAMAT.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 420, 70));

        nama1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nama1FocusGained(evt);
            }
        });
        nama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama1ActionPerformed(evt);
            }
        });
        getContentPane().add(nama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 290, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/PASSWORD.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 280, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/USERNAME.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 280, 30));

        logine.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        logine.setText("Login");
        logine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logineActionPerformed(evt);
            }
        });
        getContentPane().add(logine, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 430, 130, 40));

        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordFocusGained(evt);
            }
        });
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 290, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/login.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logineActionPerformed
//        new pinjem().setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_logineActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void nama1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nama1FocusGained
        check = false;
    }//GEN-LAST:event_nama1FocusGained

    private void passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusGained
        if (!check) {
            if (nama1.getText().equals("admin")) {
                JOptionPane.showMessageDialog(rootPane, "masukkan password untuk admin");
                check = true;
            } else if (nama1.getText().equals("jahrotus")) {
                JOptionPane.showMessageDialog(rootPane, "Masukkan NIM");
                check = true;
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "SALAH!!!!!!!!!");
                check = true;
            }
        }
    }//GEN-LAST:event_passwordFocusGained

    private void nama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginx.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginx().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton logine;
    private javax.swing.JTextField nama1;
    private javax.swing.JPasswordField password;
    // End of variables declaration//GEN-END:variables

    private class LoginListener implements ActionListener {

        public LoginListener() {
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            String user = nama1.getText();
            String pass = password.getText();
            boolean user1 = false, pass1 = false;

            if (user.equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(rootPane, "Username Harus Diisi");
            } else {
                user1 = true;
            }

            if (pass.equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(rootPane, "Password Harus Diisi");
            } else {
                pass1 = true;
            }
            if (user1 && pass1) {
                if (user.equalsIgnoreCase("admin") && pass.equalsIgnoreCase("123")) {
                    tux a = new tux();
                    a.setVisible(true);
                } else if (user.equalsIgnoreCase("jahrotus") && pass.equalsIgnoreCase("162410101065")) {
                    pinjem a = new pinjem();
                    a.setVisible(true);
                }
                
            }
        }
    }
}
