/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penyilihan;

/**
 *
 * @author Mik
 */
public class peminjamanx extends javax.swing.JPanel {

    /**
     * Creates new form peminjamanx
     */
    public peminjamanx() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nmbarang = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        kegiatan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jmlhbrng = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sub2 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        jLabel1.setText("KEGIATAN");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 114, -1, 20));

        nmbarang.setFont(new java.awt.Font("Javanese Text", 0, 12)); // NOI18N
        nmbarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sound", "Mic", "Kursi", "Proyektor", "Kabel Olor" }));
        nmbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmbarangActionPerformed(evt);
            }
        });
        add(nmbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 290, 40));

        jLabel2.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        jLabel2.setText("NAMA BARANG");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 64, -1, 20));
        add(kegiatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 290, 40));

        jLabel3.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        jLabel3.setText("HARI");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));
        add(jmlhbrng, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 290, 40));

        jLabel4.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        jLabel4.setText("JUMLAH BARANG");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        sub2.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        sub2.setText("Submit");
        add(sub2, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 270, 100, 40));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 290, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void nmbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmbarangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jmlhbrng;
    private javax.swing.JTextField kegiatan;
    private javax.swing.JComboBox<String> nmbarang;
    private javax.swing.JButton sub2;
    // End of variables declaration//GEN-END:variables
}
