/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penyilihan;

/**
 *
 * @author Mik
 */
public class peminjamanx extends javax.swing.JPanel {

    /**
     * Creates new form peminjamanx
     */
    public peminjamanx() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nmbarang = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        kegiatan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jmlhbrng = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sub2 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 102));
        setMinimumSize(new java.awt.Dimension(910, 520));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        jLabel1.setText("KEGIATAN");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, 20));

        nmbarang.setFont(new java.awt.Font("Javanese Text", 0, 12)); // NOI18N
        nmbarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sound", "Mic", "Kursi", "Proyektor", "Kabel Olor" }));
        nmbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmbarangActionPerformed(evt);
            }
        });
        add(nmbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 290, 40));

        jLabel2.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        jLabel2.setText("NAMA BARANG");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, 20));
        add(kegiatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 290, 40));

        jLabel3.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        jLabel3.setText("HARI");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));
        add(jmlhbrng, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 290, 40));

        jLabel4.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        jLabel4.setText("JUMLAH BARANG");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        sub2.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        sub2.setText("Submit");
        add(sub2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 100, 40));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 290, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("     ");
        jLabel5.setPreferredSize(new java.awt.Dimension(910, 520));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 520));
    }// </editor-fold>//GEN-END:initComponents

    private void nmbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmbarangActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jmlhbrng;
    private javax.swing.JTextField kegiatan;
    private javax.swing.JComboBox<String> nmbarang;
    private javax.swing.JButton sub2;
    // End of variables declaration//GEN-END:variables
}
