/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penyilihan;

/**
 *
 * @author Mik
 */
public class peminjamx extends javax.swing.JPanel {

    /**
     * Creates new form peminjamx
     */
    public peminjamx() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nim = new javax.swing.JTextField();
        ukm = new javax.swing.JTextField();
        sie = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        edit = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NAMA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 70, -1, -1));

        jLabel2.setText("NIM");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel3.setText("UKM");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel4.setText("SIE");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));
        add(nim, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 290, 40));
        add(ukm, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 290, 40));
        add(sie, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 290, 40));
        add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 290, 40));

        edit.setText("Logout");
        add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 100, 40));

        logout.setText("Edit");
        add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 270, 100, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton logout;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nim;
    private javax.swing.JTextField sie;
    private javax.swing.JTextField ukm;
    // End of variables declaration//GEN-END:variables
}
