/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penyilihan;

/**
 *
 * @author X
 */
public class pengembaliantux extends javax.swing.JPanel {

    /**
     * Creates new form pengembaliantux
     */
    public pengembaliantux() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        jLabel6.setText("TANGGAL PEMINJAMAN");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 180, -1));

        jLabel3.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        jLabel3.setText("BARANG");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 200, -1));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 290, 40));
        add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 290, 40));

        jButton1.setText("SUBMIT");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 290, 200));

        jLabel4.setFont(new java.awt.Font("Javanese Text", 1, 12)); // NOI18N
        jLabel4.setText("TANGGAL PENGEMBALIAN");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 200, -1));

        jButton2.setText("check");
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, -1));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 480));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
