/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penyilihan;

/**
 *
 * @author X
 */
public class peralatantux extends javax.swing.JPanel {

    /**
     * Creates new form peralatantux
     */
    public peralatantux() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        update = new javax.swing.JButton();
        create = new javax.swing.JButton();
        namaBarang = new javax.swing.JLabel();
        jumlah = new javax.swing.JLabel();
        txtBarang = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Javanese Text", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"SOUND",  new Integer(1)},
                {"MIC", null},
                {"KURSI", null},
                {"PROYEKTOR", null},
                {"KABEL OLOR", null}
            },
            new String [] {
                "NAMA BARANG", "JUMLAH BARANG TERSEDIA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(0, 153, 153));
        jScrollPane2.setViewportView(jTable1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, 150));

        update.setText("UPDATE");
        add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, -1, -1));

        create.setText("CREATE");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        namaBarang.setText("Nama Barang :");
        add(namaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jumlah.setText("Jumlah :");
        add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));
        add(txtBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 130, -1));
        add(txtJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 140, -1));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_createActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel jumlah;
    private javax.swing.JLabel namaBarang;
    private javax.swing.JTextField txtBarang;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
