/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package penyilihan;

/**
 *
 * @author X
 */
public class persetujuanx extends javax.swing.JPanel {

    /** Creates new form persetujuanx */
    public persetujuanx() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        namakegiatan = new javax.swing.JLabel();
        barang = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(910, 480));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Status");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 110, 50));

        jLabel2.setText("Nama Kegiatan");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 110, 50));

        namakegiatan.setText("......................");
        add(namakegiatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 350, 50));

        barang.setText(".......................");
        add(barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 350, 50));

        status.setText("........................");
        add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 350, 50));

        jLabel4.setText("Barang");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 110, 50));

        jLabel5.setText(":");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 20, 50));

        jLabel6.setText(":");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 20, 50));

        jLabel3.setText(":");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 20, 50));
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 480));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel namakegiatan;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables

}
